Store yearwise sales of 2 dealers for tv, freeze, mobile, washing machine, ac and diswasher for years 2001 to 2010

In [2]:
import numpy as np

In [3]:
dealer_1 = np.arange(60).reshape(10, 6)
dealer_1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [4]:
dealer_2 = np.arange(60, 120).reshape(10, 6)
dealer_2

array([[ 60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101],
       [102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113],
       [114, 115, 116, 117, 118, 119]])

find the year wise sale of each item by both the dealer

In [5]:
years = np.arange(2001, 2011)
years

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010])

In [6]:
item = ["TV", "Freeze", "Mobile", "Washing Machine", "AC", "Dishwasher"]
item

['TV', 'Freeze', 'Mobile', 'Washing Machine', 'AC', 'Dishwasher']

yearwise sale of dealer 1

In [14]:
sum_1 = np.sum(dealer_1, axis=1)
print(np.vstack((years, sum_1)))

[[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010]
 [  15   51   87  123  159  195  231  267  303  339]]


yearwise sale of dealer 2

In [15]:
sum_1 = np.sum(dealer_2, axis=1)
print(np.vstack((years, sum_1)))

[[2001 2002 2003 2004 2005 2006 2007 2008 2009 2010]
 [ 375  411  447  483  519  555  591  627  663  699]]


dealer 1 TV and freeze sale

In [18]:
print("TV ", "Freeze")
print(np.sum(dealer_1[:,0]), np.sum(dealer_1[:,1]))

TV  Freeze
270 280


dealer 2 TV and freeze sale

In [19]:
print("TV ", "Freeze")
print(np.sum(dealer_2[:,0]), np.sum(dealer_2[:,1]))

TV  Freeze
870 880


In [26]:
dic_1 = {"TV" : dealer_1[:,0], "Freeze" : dealer_1[:,1], "Mobile" : dealer_1[:,2],
         "Washing Machine" : dealer_1[:,3], "AC" : dealer_1[:,4], "Dishwasher" : dealer_1[:,5]}
print(dic_1)

{'TV': array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54]), 'Freeze': array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55]), 'Mobile': array([ 2,  8, 14, 20, 26, 32, 38, 44, 50, 56]), 'Washing Machine': array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57]), 'AC': array([ 4, 10, 16, 22, 28, 34, 40, 46, 52, 58]), 'Dishwasher': array([ 5, 11, 17, 23, 29, 35, 41, 47, 53, 59])}


In [27]:
dic_2 = {"TV" : dealer_2[:,0], "Freeze" : dealer_2[:,1], "Mobile" : dealer_2[:,2],
         "Washing Machine" : dealer_2[:,3], "AC" : dealer_2[:,4], "Dishwasher" : dealer_2[:,5]}
print(dic_2)

{'TV': array([ 60,  66,  72,  78,  84,  90,  96, 102, 108, 114]), 'Freeze': array([ 61,  67,  73,  79,  85,  91,  97, 103, 109, 115]), 'Mobile': array([ 62,  68,  74,  80,  86,  92,  98, 104, 110, 116]), 'Washing Machine': array([ 63,  69,  75,  81,  87,  93,  99, 105, 111, 117]), 'AC': array([ 64,  70,  76,  82,  88,  94, 100, 106, 112, 118]), 'Dishwasher': array([ 65,  71,  77,  83,  89,  95, 101, 107, 113, 119])}


In [28]:
dic_1["TV"]

array([ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54])